base_name: "025154a1-82dd-42d1-82a2-ff7bafbf226c"

stages:
  - test

test:
  tags:
    - why
  script:
    - mkdir -p /srv/salt
    - ln -s $PWD/caddy /srv/salt/caddy
    - salt-call --local state.apply caddy
