stages:
  - test

variables:
  SUDO_ASKPASS: /usr/bin/ssh-askpass

test:
  tags:
    - why
  script:
    - sudo mkdir -p /srv/salt
    - sudo ln -s $PWD/caddy /srv/salt/caddy
    - sudo salt-call --local state.sls caddy
    - sudo journalctl -u caddy
    - curl localhost
